import { APP_CONFIG } from '@/shared/config/app';
import type { Task, TaskCategory } from '../model/types';

type Seed = Omit<Task, 'category' | 'status'> & { status?: Task['status'] };
const make = (category: TaskCategory, list: Seed[]): Task[] =>
  list.map(({ status, ...rest }) => ({
    ...rest,
    category,
    status: status ?? 'in-progress',
  }));

const DAILY: Task[] = make('daily', [
  {
    id: 'd-play-1',
    kind: 'play-one-game',
    title: 'Сыграй одну игру',
    description: 'Заверши хотя бы одну сессию сегодня',
    reward: 30,
    progress: { current: 0, total: 1 },
  },
  {
    id: 'd-fav-1',
    kind: 'favorite-questions',
    title: 'Отметь вопрос звёздочкой',
    description: 'Сохрани понравившийся вопрос в избранное',
    reward: 20,
    progress: { current: 0, total: 1 },
  },
  {
    id: 'd-followup-3',
    kind: 'use-followup',
    title: '3 уточняющих вопроса',
    description: 'Используй «Уточнить» в карточке вопроса',
    reward: 25,
    progress: { current: 1, total: 3 },
  },
  {
    id: 'd-streak-1',
    kind: 'daily-streak',
    title: 'Зайди в приложение',
    description: 'Лёгкое задание — ты уже его выполнил',
    reward: 15,
    progress: { current: 1, total: 1 },
  },
  {
    id: 'd-questions-10',
    kind: 'play-multiple-games',
    title: 'Пройди 10 вопросов',
    description: 'В одной или нескольких играх',
    reward: 40,
    progress: { current: 3, total: 10 },
  },
  {
    id: 'd-friends-deck',
    kind: 'play-one-game',
    title: 'Сыграй колодой «Друзья»',
    description: 'Конкретно эту колоду — для бонуса',
    reward: 35,
    progress: { current: 0, total: 1 },
  },
  {
    id: 'd-rate',
    kind: 'rate-game',
    title: 'Поставь оценку игре',
    description: 'Помоги нам — оставь фидбек',
    reward: 25,
    progress: { current: 0, total: 1 },
  },
  {
    id: 'd-self-deck',
    kind: 'play-one-game',
    title: 'Загляни в «Я и Я»',
    description: 'Колода для саморефлексии',
    reward: 30,
    progress: { current: 0, total: 1 },
  },
  {
    id: 'd-share',
    kind: 'share-app',
    title: 'Поделись приложением',
    description: 'Расскажи о ToKnow одному человеку',
    reward: 20,
    progress: { current: 0, total: 1 },
  },
  {
    id: 'd-favorites-3',
    kind: 'favorite-questions',
    title: '3 вопроса в избранное',
    description: 'Собирай свою личную колоду',
    reward: 35,
    progress: { current: 0, total: 3 },
  },
]);

const WEEKLY: Task[] = make('weekly', [
  {
    id: 'w-streak-5',
    kind: 'daily-streak',
    title: `Заходи ${APP_CONFIG.streakRequiredDays} дней подряд`,
    description: 'Серия посещений — каждый день засчитывается одним заходом',
    reward: 200,
    progress: { current: 2, total: APP_CONFIG.streakRequiredDays },
  },
  {
    id: 'w-channel',
    kind: 'subscribe-channel',
    title: 'Подпишись на наш канал',
    description: 'Будь в курсе новых колод и обновлений',
    reward: 80,
    progress: { current: 0, total: 1 },
    ctaUrl: APP_CONFIG.channelLink,
  },
  {
    id: 'w-invite-5',
    kind: 'invite-friends',
    title: `Пригласи ${APP_CONFIG.invitesRequired} друзей`,
    description: 'Приглашённые должны запустить приложение',
    reward: 300,
    progress: { current: 1, total: APP_CONFIG.invitesRequired },
  },
  {
    id: 'w-play-7',
    kind: 'play-multiple-games',
    title: 'Сыграй 7 игр за неделю',
    description: 'Усреднённо — игра в день',
    reward: 250,
    progress: { current: 2, total: 7 },
  },
  {
    id: 'w-buy-deck',
    kind: 'buy-deck',
    title: 'Купи одну новую колоду',
    description: 'Открой новые темы для разговоров',
    reward: 150,
    progress: { current: 0, total: 1 },
  },
  {
    id: 'w-buy-char',
    kind: 'buy-character',
    title: 'Купи нового героя',
    description: 'Расширь свою коллекцию',
    reward: 180,
    progress: { current: 0, total: 1 },
  },
  {
    id: 'w-favorites-10',
    kind: 'favorite-questions',
    title: '10 вопросов в избранное',
    description: 'За всю неделю',
    reward: 120,
    progress: { current: 1, total: 10 },
  },
  {
    id: 'w-finish-deck',
    kind: 'finish-deck',
    title: 'Заверши колоду до конца',
    description: 'Пройди все вопросы одной колоды',
    reward: 220,
    progress: { current: 0, total: 1 },
  },
  {
    id: 'w-three-decks',
    kind: 'play-multiple-games',
    title: 'Сыграй тремя разными колодами',
    description: 'Разнообразие — ключ к близости',
    reward: 180,
    progress: { current: 1, total: 3 },
  },
  {
    id: 'w-followup-10',
    kind: 'use-followup',
    title: '10 уточняющих вопросов',
    description: 'За неделю',
    reward: 140,
    progress: { current: 2, total: 10 },
  },
]);

const CHALLENGES: Task[] = make('challenge', [
  {
    id: 'c-collect-6',
    kind: 'buy-character',
    title: 'Собери всех 6 героев',
    description: 'Полная коллекция — +50% бонус ко всему',
    reward: 1500,
    progress: { current: 2, total: 6 },
  },
  {
    id: 'c-collect-decks',
    kind: 'buy-deck',
    title: 'Собери все колоды',
    description: 'И платные, и особые',
    reward: 1000,
    progress: { current: 4, total: 7 },
  },
  {
    id: 'c-streak-30',
    kind: 'daily-streak',
    title: 'Зайди 30 дней подряд',
    description: 'Серьёзный челлендж',
    reward: 2000,
    progress: { current: 2, total: 30 },
  },
  {
    id: 'c-invite-25',
    kind: 'invite-friends',
    title: 'Пригласи 25 друзей',
    description: 'Расскажи всему городу',
    reward: 2500,
    progress: { current: 1, total: 25 },
  },
  {
    id: 'c-play-100',
    kind: 'play-multiple-games',
    title: '100 сыгранных игр',
    description: 'Долгая дистанция',
    reward: 3000,
    progress: { current: 2, total: 100 },
  },
  {
    id: 'c-night-master',
    kind: 'finish-deck',
    title: 'Мастер ночи',
    description: 'Пройди колоду «Поздняя ночь» 5 раз',
    reward: 800,
    progress: { current: 0, total: 5 },
    status: 'locked',
  },
  {
    id: 'c-couple-master',
    kind: 'finish-deck',
    title: 'Мастер близости',
    description: 'Пройди колоду «Пара» 10 раз',
    reward: 1200,
    progress: { current: 0, total: 10 },
  },
  {
    id: 'c-favorites-100',
    kind: 'favorite-questions',
    title: '100 любимых вопросов',
    description: 'Личная антология',
    reward: 900,
    progress: { current: 3, total: 100 },
  },
  {
    id: 'c-feedback-master',
    kind: 'rate-game',
    title: 'Дай 5 фидбеков',
    description: 'Помоги нам делать продукт лучше',
    reward: 500,
    progress: { current: 1, total: 5 },
  },
  {
    id: 'c-rare-hunter',
    kind: 'buy-character',
    title: 'Охотник за редкими',
    description: 'Открой 3 редких или выше героев',
    reward: 700,
    progress: { current: 1, total: 3 },
  },
]);

const ALL_TASKS: Task[] = [...DAILY, ...WEEKLY, ...CHALLENGES];

export const taskRepository = {
  list: async (): Promise<Task[]> => Promise.resolve(ALL_TASKS),
  byCategory: async (cat: TaskCategory) =>
    ALL_TASKS.filter((t) => t.category === cat),
};
