import type { Question } from '@/entities/question';
import type { Deck, DeckGroup } from '../model/types';

const GROUPS: DeckGroup[] = [
  {
    id: 'classic',
    title: 'Классика',
    emoji: '🌿',
    description: 'Вопросы на каждый день',
    gradient: 'from-emerald-400 to-teal-500',
  },
  {
    id: 'love',
    title: 'Близость',
    emoji: '💞',
    description: 'Для пар и тех, кто рядом',
    gradient: 'from-rose-400 to-pink-500',
  },
  {
    id: 'special',
    title: 'Особое',
    emoji: '✨',
    description: 'Платные и тематические колоды',
    gradient: 'from-violet-400 to-fuchsia-500',
  },
];

const q = (deckId: string, items: { id: string; text: string; followUp?: string }[]): Question[] =>
  items.map((it) => ({ deckId, ...it }));

const DECKS: Deck[] = [
  // ── classic ────────────────────────────────────────────────
  {
    id: 'friends',
    groupId: 'classic',
    title: 'Друзья',
    cover: '🫂',
    background: 'from-emerald-400 to-emerald-600',
    cardBackground: 'from-emerald-500 via-emerald-600 to-teal-700',
    cardTextColor: 'text-white',
    kind: 'free',
    questions: q('friends', [
      { id: 'f1', text: 'За что ты благодарен мне в нашей дружбе?', followUp: 'Какой момент вспоминаешь чаще всего?' },
      { id: 'f2', text: 'Что я никогда не узнаю о тебе, если ты сам не расскажешь?' },
      { id: 'f3', text: 'Какой совет ты бы дал себе пятилетней давности?', followUp: 'А десятилетней?' },
      { id: 'f4', text: 'Что для тебя значит «настоящая дружба»?' },
      { id: 'f5', text: 'Какое моё качество ты бы хотел перенять?' },
      { id: 'f6', text: 'О чём ты молчал последний месяц?', followUp: 'Почему именно об этом?' },
      { id: 'f7', text: 'Какая мечта кажется тебе сейчас невозможной?' },
      { id: 'f8', text: 'Когда последний раз ты по-настоящему гордился собой?' },
      { id: 'f9', text: 'Что мы могли бы сделать вместе, чтобы стать ближе?' },
      { id: 'f10', text: 'Что в твоей жизни сейчас просит больше внимания?' },
    ]),
  },
  {
    id: 'family',
    groupId: 'classic',
    title: 'Семья',
    cover: '🏡',
    background: 'from-amber-400 to-orange-600',
    cardBackground: 'from-amber-500 via-orange-600 to-rose-600',
    cardTextColor: 'text-white',
    kind: 'free',
    questions: q('family', [
      { id: 'fa1', text: 'Какой семейный ритуал ты бы хотел сохранить навсегда?' },
      { id: 'fa2', text: 'Что родители недооценили в тебе в детстве?', followUp: 'А что переоценили?' },
      { id: 'fa3', text: 'Кому из родственников ты до сих пор не сказал «спасибо»?' },
      { id: 'fa4', text: 'Чему тебя научила семья — без слов?' },
      { id: 'fa5', text: 'Какое детское воспоминание стало твоей опорой?' },
      { id: 'fa6', text: 'Что бы ты сказал своему внутреннему ребёнку сегодня?' },
      { id: 'fa7', text: 'Какая семейная история повторяется из поколения в поколение?' },
      { id: 'fa8', text: 'О чём ты бы хотел поговорить с родителями, но не решаешься?' },
      { id: 'fa9', text: 'Что в своих детях ты бы хотел воспитать иначе, чем в тебе?' },
    ]),
  },
  {
    id: 'self',
    groupId: 'classic',
    title: 'Я и Я',
    cover: '🪞',
    background: 'from-sky-400 to-blue-600',
    cardBackground: 'from-sky-500 via-blue-600 to-indigo-700',
    cardTextColor: 'text-white',
    kind: 'free',
    questions: q('self', [
      { id: 's1', text: 'Каким ты будешь через 10 лет — если перестанешь себя сдерживать?' },
      { id: 's2', text: 'Что ты прощаешь себе сегодня?', followUp: 'А что пока не получается простить?' },
      { id: 's3', text: 'Какая твоя суперсила, которую ты ещё не назвал вслух?' },
      { id: 's4', text: 'От чего ты бежал последние полгода?' },
      { id: 's5', text: 'Что тебе хотелось бы услышать прямо сейчас?' },
      { id: 's6', text: 'Чьё мнение всё ещё слишком сильно тебя задевает?' },
      { id: 's7', text: 'Что ты делаешь, когда никто не видит — и собой гордишься?' },
      { id: 's8', text: 'Какое решение ты откладываешь уже слишком долго?' },
      { id: 's9', text: 'Что для тебя признак того, что ты на правильном пути?' },
      { id: 's10', text: 'Какая часть тебя всё ещё ждёт разрешения существовать?' },
    ]),
  },

  // ── love ───────────────────────────────────────────────────
  {
    id: 'couple',
    groupId: 'love',
    title: 'Пара',
    cover: '💑',
    background: 'from-rose-500 to-pink-700',
    cardBackground: 'from-rose-600 via-pink-600 to-fuchsia-700',
    cardTextColor: 'text-white',
    kind: 'free',
    questions: q('couple', [
      { id: 'c1', text: 'Когда ты в последний раз чувствовал нас как одну команду?' },
      { id: 'c2', text: 'Что во мне ты замечаешь, но никогда не говоришь вслух?', followUp: 'Почему молчишь?' },
      { id: 'c3', text: 'Какое наше совместное приключение ты хочешь повторить?' },
      { id: 'c4', text: 'О какой нашей мечте ты думаешь чаще всего?' },
      { id: 'c5', text: 'Что я могу делать чаще, чтобы тебе было теплее?' },
      { id: 'c6', text: 'В чём ты бы хотел больше доверия — моего или своего?' },
      { id: 'c7', text: 'Какой страх ты бы хотел разделить со мной?' },
      { id: 'c8', text: 'Где в наших отношениях ты чувствуешь себя самым собой?' },
      { id: 'c9', text: 'Что я недавно сделал, и это тебя тронуло?' },
      { id: 'c10', text: 'Какую ссору ты бы переиграл и почему?' },
    ]),
  },
  {
    id: 'date',
    groupId: 'love',
    title: 'Первое свидание',
    cover: '☕️',
    background: 'from-pink-400 to-rose-500',
    cardBackground: 'from-pink-500 via-rose-600 to-red-600',
    cardTextColor: 'text-white',
    kind: 'paid',
    price: { amount: 200, currency: 'COIN' },
    questions: q('date', [
      { id: 'd1', text: 'Что ты надеешься узнать обо мне за этот вечер?' },
      { id: 'd2', text: 'Какая твоя самая странная привычка?' },
      { id: 'd3', text: 'Где и как у тебя лучше всего отдыхает мозг?' },
      { id: 'd4', text: 'О чём ты можешь говорить часами?' },
      { id: 'd5', text: 'Каким ребёнком ты был?' },
      { id: 'd6', text: 'Что было лучшим решением в твоей жизни?' },
      { id: 'd7', text: 'Какая черта в людях сразу располагает?' },
      { id: 'd8', text: 'О чём ты мечтал в 16, и что из этого сбылось?' },
    ]),
  },

  // ── special ────────────────────────────────────────────────
  {
    id: 'late-night',
    groupId: 'special',
    title: 'Поздняя ночь',
    cover: '🌙',
    background: 'from-indigo-700 to-purple-900',
    cardBackground: 'from-indigo-900 via-purple-900 to-slate-900',
    cardTextColor: 'text-amber-100',
    kind: 'special',
    price: { amount: 300, currency: 'COIN' },
    questions: q('late-night', [
      { id: 'n1', text: 'О чём ты думаешь, когда не можешь уснуть?' },
      { id: 'n2', text: 'Какой сон возвращается к тебе чаще всего?' },
      { id: 'n3', text: 'Что бы ты сделал, если бы никто не узнал?' },
      { id: 'n4', text: 'Какая правда о себе тебя пугает?', followUp: 'А что тебя в ней пугает больше всего?' },
      { id: 'n5', text: 'Где живёт твоё одиночество?' },
      { id: 'n6', text: 'О чём ты молишься, даже если не веришь?' },
      { id: 'n7', text: 'Что бы ты хотел оставить в этой ночи навсегда?' },
      { id: 'n8', text: 'Что для тебя значит быть по-настоящему услышанным?' },
    ]),
  },
  {
    id: 'roots',
    groupId: 'special',
    title: 'Корни',
    cover: '🌳',
    background: 'from-stone-500 to-stone-800',
    cardBackground: 'from-stone-700 via-stone-800 to-zinc-900',
    cardTextColor: 'text-amber-50',
    kind: 'special',
    price: { amount: 450, currency: 'COIN' },
    questions: q('roots', [
      { id: 'r1', text: 'Что в твоей семье передаётся из поколения в поколение?' },
      { id: 'r2', text: 'Кого из предков ты бы хотел узнать лично?' },
      { id: 'r3', text: 'Какая семейная история кажется тебе мифом?' },
      { id: 'r4', text: 'Какую традицию ты бы хотел начать сам?' },
      { id: 'r5', text: 'Чего тебе не хватало в детстве — и есть сейчас?' },
      { id: 'r6', text: 'Что важного ты унаследовал — но никогда не благодарил за это?' },
      { id: 'r7', text: 'Какое место ты называешь «домом» — и почему?' },
    ]),
  },
];

export const deckRepository = {
  groups: async (): Promise<DeckGroup[]> => Promise.resolve(GROUPS),
  list: async (): Promise<Deck[]> => Promise.resolve(DECKS),
  byGroup: async (groupId: string) =>
    DECKS.filter((d) => d.groupId === groupId),
  byId: async (id: string) => DECKS.find((d) => d.id === id) ?? null,
};
